name: Deploy to VPS

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Install & Connect Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-actions
          sudo tailscale ip -4 -o tailscale_ip.txt
          cat tailscale_ip.txt
          
      - name: Debug SSH Key
        if: github.ref == 'refs/heads/development'
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" | base64

      - name: Setup SSH & Deploy ke VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22  
          script: |
            cd ~/moneyflow/docker/backend
            git pull origin main
            docker compose down
            docker compose up -d --build
